COMMENT *
	Antet pentru biblioteca libc
	!Implementata partiala!
	Copyright Cemirtan Cristian 2021
*

INCLUDE stdlibm.inc

EXTRN digitcount : PROC
EXTRN udigitcount : PROC
EXTRN wtos : PROC
EXTRN uwtos : PROC
EXTRN atoi : PROC
EXTRN strcpy : PROC
EXTRN strncpy : PROC
EXTRN memcpy : PROC
EXTRN memset : PROC
EXTRN strlen : PROC
EXTRN printf : PROC
EXTRN sprintf : PROC
EXTRN scanf : PROC
EXTRN puts : PROC
EXTRN gets : PROC
EXTRN getchar : PROC